name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: aliyun8879165869
        password: wsz5207208
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        skopeo copy docker-daemon:lubo1994/pv-hawk:latest docker://registry.cn-hangzhou.aliyuncs.com/aliyun8879165869/sun-panel:1.4.0
    
