name: Build and Push Docker Image to Aliyun

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install Latest Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Install Skopeo
      run: sudo apt-get install -y skopeo

    - name: Log in to Aliyun Docker Registry
      run: |
        echo wsz5207208 | docker login registry.cn-hangzhou.aliyuncs.com -u aliyun8879165869 --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t registry.cn-hangzhou.aliyuncs.com/wushizhen/sun-panel:latest .
        docker push registry.cn-hangzhou.aliyuncs.com/wushizhen/sun-panel:latest
